### ISSUE TITLE
[Actual Bug] Foreign key constraint failed on the field: `foreign key`

### ISSUE THREAD

**Issue by FuckingToasters** [HemmeligOrg/Hemmelig.app#216]
### Description

When trying to upload a file, the error in the title happens. statuscode is 500: internal server error.

Logs show following (I manually removed some timestamps so it's easier to read):
```
> hemmelig@5.0.0 start
> prisma migrate deploy && node server.js
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "hemmelig.db" at "file:../database/hemmelig.db"
SQLite database hemmelig.db created at file:../database/hemmelig.db
13 migrations found in prisma/migrations
Applying migration `20230403094651_init`
Applying migration `20230403105353_init`
Applying migration `20230405075854_usergenerated`
Applying migration `20230405082548_userrole`
Applying migration `20230406072002_settings`
Applying migration `20230406095057_readonly`
Applying migration `20230409114406_disablefileupload`
Applying migration `20230409162446_cascadedelete`
Applying migration `20230411070916_disable_account_creation`
Applying migration `20230415103015_user_secret_relation`
Applying migration `20230417053342_org_email_setting`
Applying migration `20230417111804_rename_restrict`
Applying migration `20230421090823_secretid_uuid`
The following migrations have been applied:
migrations/
  └─ 20230403094651_init/
    └─ migration.sql
  └─ 20230403105353_init/
    └─ migration.sql
  └─ 20230405075854_usergenerated/
    └─ migration.sql
  └─ 20230405082548_userrole/
    └─ migration.sql
  └─ 20230406072002_settings/
    └─ migration.sql
  └─ 20230406095057_readonly/
    └─ migration.sql
  └─ 20230409114406_disablefileupload/
    └─ migration.sql
  └─ 20230409162446_cascadedelete/
    └─ migration.sql
  └─ 20230411070916_disable_account_creation/
    └─ migration.sql
  └─ 20230415103015_user_secret_relation/
    └─ migration.sql
  └─ 20230417053342_org_email_setting/
    └─ migration.sql
  └─ 20230417111804_rename_restrict/
    └─ migration.sql
  └─ 20230421090823_secretid_uuid/
    └─ migration.sql
      
All migrations have been successfully applied.
2023/09/28 10:08PM 2023/09/28 10:08PM 30 2023/09/28 10:08PM 2023/09/28 10:08PM 30 2023/09/28 10:08PM 2023/09/28 10:08PM 30 2023/09/28 10:08PM 2023/09/28 10:08PM 30 2023/09/28 10:08PM 2023/09/28 10:08PM 30 2023/09/28 10:08PM 2023/09/28 10:08PM 30 2023/09/28 10:08PM 2023/09/28 10:08PM 30 2023/09/28 10:08PM 2023/09/28 10:08PM 30 pid=20 2023/09/28 10:08PM 2023/09/28 10:08PM 30 2023/09/28 10:08PM 2023/09/28 10:08PM 30 2023/09/28 10:08PM 2023/09/28 10:08PM 30 2023/09/28 10:08PM 2023/09/28 10:08PM 30 2023/09/28 10:08PM 2023/09/28 10:08PM 30 2023/09/28 10:08PM 2023/09/28 10:08PM 30 2023/09/28 10:08PM 2023/09/28 10:08PM 30 2023/09/28 10:08PM 2023/09/28 10:08PM 30 pid=20 hostname=hemmelig 2023/09/28 10:08PM 2023/09/28 10:08PM 30 2023/09/28 10:08PM 2023/09/28 10:08PM 30 2023/09/28 10:08PM 2023/09/28 10:08PM 30 2023/09/28 10:08PM 2023/09/28 10:08PM 30 2023/09/28 10:08PM 2023/09/28 10:08PM 30 2023/09/28 10:08PM 2023/09/28 10:08PM 30 2023/09/28 10:08PM 2023/09/28 10:08PM 30 2023/09/28 10:08PM 2023/09/28 10:08PM 30 pid=20 2023/09/28 10:08PM 2023/09/28 10:08PM 30 2023/09/28 10:08PM 2023/09/28 10:08PM 30 2023/09/28 10:08PM 2023/09/28 10:08PM 30 2023/09/28 10:08PM 2023/09/28 10:08PM 30 2023/09/28 10:08PM 2023/09/28 10:08PM 30 2023/09/28 10:08PM 2023/09/28 10:08PM 30 2023/09/28 10:08PM 2023/09/28 10:08PM 30 2023/09/28 10:08PM 2023/09/28 10:08PM 30 pid=20 hostname=hemmelig msg=Server listening at http://0.0.0.0:3000
(node:20) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
50 2023/09/28 10:09PM 2023/09/28 10:09PM 50 2023/09/28 10:09PM 2023/09/28 10:09PM 50 2023/09/28 10:09PM 2023/09/28 10:09PM 50 2023/09/28 10:09PM 2023/09/28 10:09PM 50 2023/09/28 10:09PM 2023/09/28 10:09PM 50 2023/09/28 10:09PM 2023/09/28 10:09PM 50 pid=20 hostname=hemmelig 2023/09/28 10:09PM 2023/09/28 10:09PM 50 2023/09/28 10:09PM 2023/09/28 10:09PM 50 2023/09/28 10:09PM 2023/09/28 10:09PM 50 2023/09/28 10:09PM 2023/09/28 10:09PM 50 2023/09/28 10:09PM 2023/09/28 10:09PM 50 2023/09/28 10:09PM 2023/09/28 10:09PM 50 2023/09/28 10:09PM 2023/09/28 10:09PM 50 2023/09/28 10:09PM 2023/09/28 10:09PM 50 pid=20 2023/09/28 10:09PM 2023/09/28 10:09PM 50 2023/09/28 10:09PM 2023/09/28 10:09PM 50 2023/09/28 10:09PM 2023/09/28 10:09PM 50 2023/09/28 10:09PM 2023/09/28 10:09PM 50 2023/09/28 10:09PM 2023/09/28 10:09PM 50 2023/09/28 10:09PM 2023/09/28 10:09PM 50 2023/09/28 10:09PM 2023/09/28 10:09PM 50 2023/09/28 10:09PM 2023/09/28 10:09PM 50 pid=20 hostname=hemmelig reqId=req-5 req={"method":"POST","url":"/api/secret","hostname":"files.vbucksgenerator.zip","remoteAddress":"172.26.0.8","remotePort":32814} res={"statusCode":500} err={"type":"PrismaClientKnownRequestError","message":"\nInvalid `prisma.secret.create()` invocation:\n\n\nForeign key constraint failed on the field: `foreign key`","stack":"Error: \nInvalid `prisma.secret.create()` invocation:\n\n\nForeign key constraint failed on the field: `foreign key`\n    at fn.handleRequestError (/home/node/hemmelig/node_modules/@prisma/client/runtime/library.js:174:6477)\n    at fn.handleAndLogRequestError (/home/node/hemmelig/node_modules/@prisma/client/runtime/library.js:174:5907)\n    at fn.request (/home/node/hemmelig/node_modules/@prisma/client/runtime/library.js:174:5786)\n    at async t._request (/home/node/hemmelig/node_modules/@prisma/client/runtime/library.js:177:10477)\n    at async Object.<anonymous> (file:///home/node/hemmelig/src/server/controllers/secret.js:142:28)","code":"P2003","clientVersion":"4.12.0","meta":{"field_name":"foreign key"}} msg=
Invalid `prisma.secret.create()` invocation:


Foreign key constraint failed on the field: `foreign key`
30 2023/09/28 10:09PM 2023/09/28 10:09PM 30 2023/09/28 10:09PM 2023/09/28 10:09PM 30 2023/09/28 10:09PM 2023/09/28 10:09PM 30 2023/09/28 10:09PM 2023/09/28 10:09PM 30 2023/09/28 10:09PM 2023/09/28 10:09PM 30 2023/09/28 10:09PM 2023/09/28 10:09PM 30 2023/09/28 10:09PM 2023/09/28 10:09PM 30 pid=20 hostname=hemmelig 2023/09/28 10:09PM 2023/09/28 10:09PM 30 2023/09/28 10:09PM 2023/09/28 10:09PM 30 2023/09/28 10:09PM 2023/09/28 10:09PM 30 2023/09/28 10:09PM 2023/09/28 10:09PM 30 2023/09/28 10:09PM 2023/09/28 10:09PM 30 2023/09/28 10:09PM 2023/09/28 10:09PM 30 2023/09/28 10:09PM 2023/09/28 10:09PM 30 2023/09/28 10:09PM 2023/09/28 10:09PM 30 pid=20 2023/09/28 10:09PM 2023/09/28 10:09PM 30 2023/09/28 10:09PM 2023/09/28 10:09PM 30 2023/09/28 10:09PM 2023/09/28 10:09PM 30 2023/09/28 10:09PM 2023/09/28 10:09PM 30 2023/09/28 10:09PM 2023/09/28 10:09PM 30 2023/09/28 10:09PM 2023/09/28 10:09PM 30 2023/09/28 10:09PM 2023/09/28 10:09PM 30 2023/09/28 10:09PM 2023/09/28 10:09PM 30 pid=20 hostname=hemmelig reqId=req-5 res={"statusCode":500} responseTime=30.20481586456299 msg=request completed
`````

**Comment by bjarneo** [comment]
I have a feeling you already have some kind of data in the database, and then you are trying to either recreate/override it when you start the docker container.

If you try to delete / start fresh with the database sqlite file, you will not get this issue.
